version: '3.9'
services:
  budge:
    container_name: container_budge
    image: linuxserver/budge:latest
    hostname: budge
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Cuiaba
    volumes:
      - ./budge/config:/config
    ports:
      - 80:80
      - 443:443
    network_mode: host