version: '3.9'

services:
#
  samba4addc:
    build: .
    container_name: container_samba4addc
    image: samba4addc
    hostname: smbd
    # restart: unless-stopped
    privileged: true
    networks:
      NET_LOCAL:
        ipv4_address: 10.100.212.64
#

#NETWORK CONFIGURATION
networks:
  NET_LOCAL:
    name: NET_LOCAL
    driver: bridge
  NET_212:
    name: NET_212
    driver: macvlan
    driver_opts: 
      parent: eno1
    #   macvlan_mode: bridge
    ipam:
      config:
        -
          subnet: 10.100.212.0/24
          gateway: 10.100.212.1
          aux_addresses:
            host: 10.100.212.65
#