FROM centos:centos8.4.2105

ARG SAMBA_VERSION=4.16.3

RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
RUN yum update -y && yum install -y dnf-plugins-core && yum install -y epel-release
RUN yum -v repolist all
RUN yum config-manager --set-enabled PowerTools -y || \
    yum config-manager --set-enabled powertools -y
RUN yum config-manager --set-enabled Devel -y || \
    yum config-manager --set-enabled devel -y
RUN yum update -y
RUN yum install -y acl attr autoconf avahi-devel bind bind-utils cups-devel curl dbus-devel gcc gzip krb5-devel
RUN yum install -y libacl-devel libarchive-devel libattr-devel libblkid-devel libbsd-devel libcap-devel libcephfs-devel libicu-devel
RUN yum install -y libpcap-devel libtasn1-devel libtasn1-tools libtirpc-devel libunwind-devel libuuid-devel libxslt 
RUN yum install -y mingw64-gcc ncurses-devel openldap-devel pam-devel patch 
RUN yum install -y perl perl-Archive-Tar perl-ExtUtils-MakeMaker perl-JSON perl-Parse-Yapp perl-Test-Simple perl-generators perl-interpreter
RUN yum install -y pkgconfig popt-devel procps-ng psmisc
RUN yum install -y python3 python3-cryptography python3-devel python3-dns python3-gpg python3-iso8601 python3-libsemanage python3-markdown python3-policycoreutils python3-pyasn1 python3-setproctitle
RUN yum install -y rsync sed sudo systemd-devel tar tracker-devel tree wget which xfsprogs-devel yum-utils zlib-devel supervisor

RUN yum clean all    

RUN wget https://download.samba.org/pub/samba/stable/samba-$SAMBA_VERSION.tar.gz
RUN tar -xvf samba-$SAMBA_VERSION.tar.gz 
# RUN cd samba-$SAMBA_VERSION && RUN ./configure --prefix /usr --enable-fhs --sysconfdir=/etc --localstatedir=/var --with-privatedir=/var/lib/samba/private --with-piddir=/var/run/samba --with-automount --datadir=/usr/share --with-lockdir=/var/run/samba --with-statedir=/var/lib/samba --with-cachedir=/var/cache/samba
# RUN make -j4 && make install 
# RUN rm -rf ./samba-$SAMBA_VERSION*

COPY nsswitch.conf /etc/nsswitch.conf
COPY named.conf /etc/named.conf
RUN chown named:named /etc/named.conf
RUN echo 'OPTIONS="-4"' >> /etc/sysconfig/named

RUN ln -s /usr/lib/libnss_winbind.so.2 /lib64/
RUN ln -s /lib64/libnss_winbind.so.2 /lib64/libnss_winbind.so
RUN ldconfig

RUN rm -rf /etc/samba/smb.conf

ADD entrypoint.sh /entrypoint.sh
COPY supervisord.conf /etc/supervisord.d/supervisord.conf
RUN chmod +x /entrypoint.sh

# ENTRYPOINT ["/entrypoint.sh"]
# CMD ["samba"]