version: '3.9'
services:
  registry:
    container_name: container_registry
    image: registry:latest
    hostname: registry
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/registry
    ports:
      - 5000:5000
    network_mode: host