version: '3.9'
services:
  vaultwarden:
    container_name: container_vaultwarden
    image: truecharts/vaultwarden:latest
    hostname: vaultwarden
    restart: always
    volumes:
      - ./data:/data
    ports:
      - 80:80
      - 3012:3012
    network_mode: host