version: '3.9'

services:
#ALPINE Teste
  alpine:
    build: .
    container_name: container_dk
    image: dk
    hostname: dk
    # restart: unless-stopped
    privileged: true
    cap_add:
      - NET_ADMIN
    #   - SYS_ADMIN
    networks:
      NET_212:
        ipv4_address: 10.100.212.63
#
#NETWORK CONFIGURATION
networks:
  # NET_LOCAL:
  #   name: NET_LOCAL
  #   driver: bridge
  NET_212:
    name: NET_212
    driver: macvlan
    driver_opts: 
      parent: eno1
    #   macvlan_mode: bridge
    ipam:
      config:
        -
          subnet: 10.100.212.0/24
          gateway: 10.100.212.1
          aux_addresses:
            host: 10.100.212.65
#