version: '3.8'

services:
#Server MINIO Teste
  serverminio:
    image: bitnami/minio:latest
    container_name: container_serverminio
    environment:
      - MINIO_ROOT_USER=kelsey
      - MINIO_ROOT_PASSWORD=kelseysantos
    volumes:
      - ./storages/minio:/data
      - ./storages/minio/certs:/certs
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      green:
#Cliente MINIO Teste
  clientminio:
    image: bitnami/minio-client:latest
    container_name: container_clientminio
    environment:
      - MINIO_SERVER_HOST="serverminio"
      - MINIO_SERVER_ACCESS_KEY="EeyKGV8sW6eNbq2o"
      - MINIO_SERVER_SECRET_KEY="gIxr84JBcWiZ7pKfScS8zNl6Spkc3I5D"
    networks:
      green:
#MINIOFIM
networks:
  green:
    name: networkgreen
    driver: bridge
  
