version: '3.8'

services:
  miniomaster:
    image: bitnami/minio:latest
    container_name: container_miniomaster
    hostname: miniomaster
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - './minio/disk0:/data'
    environment:
      - MINIO_ROOT_USER=kelsey
      - MINIO_ROOT_PASSWORD=kelseysantos
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=miniomaster,minioslave0,minioslave1,minioslave2
    networks:
      green:
      vlan10:
        ipv4_address: 10.1.10.10
  minioslave0:
    image: bitnami/minio:latest
    volumes:
      - './minio/disk1:/data'
    environment:
      - MINIO_ROOT_USER=kelsey
      - MINIO_ROOT_PASSWORD=kelseysantos
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=miniomaster,minioslave0,minioslave1,minioslave2
    networks:
      vlan10:
        ipv4_address: 10.1.10.11
  minioslave1:
    image: bitnami/minio:latest
    volumes:
      - './minio/disk2:/data'
    environment:
      - MINIO_ROOT_USER=kelsey
      - MINIO_ROOT_PASSWORD=kelseysantos
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=miniomaster,minioslave0,minioslave1,minioslave2
    networks:
      vlan10:
        ipv4_address: 10.1.10.12
  minioslave2:
    image: bitnami/minio:latest
    volumes:
      - './minio/disk3:/data'
    environment:
      - MINIO_ROOT_USER=kelsey
      - MINIO_ROOT_PASSWORD=kelseysantos
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=miniomaster,minioslave0,minioslave1,minioslave2
    networks:
      vlan10:
        ipv4_address: 10.1.10.13

networks:
  vlan10:
    name: NET_vlan10
    driver: ipvlan
    driver_opts:
      parent: eth0.10
      mode: l3
    ipam:
      config:
        - subnet: 10.1.10.0/24
  green:
    name: NET_green
    driver: bridge