version: '3.9'

services:
#
  urbackup:
    container_name: container_urbackup
    image: uroni/urbackup-server
    hostname: urbackup
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    volumes:
      - ./volumes/urbackup/backups:/backups
      - ./volumes/urbackup/share:/usr/share/urbackup
      - ./volumes/urbackup/log:/var/log
      - ./volumes/urbackup/varurbackup:/var/urbackup
    networks:
      - NET_212
    ports:
      - 55414:55414
#
#Status Docker
  doku:
    container_name: container_doku
    image: amerkurev/doku
    hostname: doku
    # cap_add:
    #   - NET_ADMIN
    #   - SYS_ADMIN 
    # restart: unless-stopped
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/:/hostroot:ro'
    ports:
      - '9090:9090'
    networks:
      - NET_LOCAL
#
#NETWORK CONFIGURATION
networks:
  NET_LOCAL:
    name: NET_LOCAL
    driver: bridge
  NET_212:
    name: NET_212
    driver: macvlan
    driver_opts: 
      parent: eno1
    #   macvlan_mode: bridge
    ipam:
      config:
        -
          subnet: 10.100.212.0/24
          gateway: 10.100.212.1
          aux_addresses:
            host: 10.100.212.65
# ip link add mynet-shim link eno1 type macvlan mode bridge
# ip addr add 10.100.212.65/32 dev mynet-shim
# ip link set mynet-shim up
# ip route add 10.100.212.0/24 dev mynet-shim
#