version: '3.9'
services:
  tomcat:
    build: .
    container_name: container_tomcat
    image: kelseysantos/tomcat10-jdk8:latest
    hostname: tomcat
    restart: unless-stopped
    privileged: true
    cap_add:
      - NET_ADMIN
    # environment:
    #   - PUID=1000
    #   - PGID=1000
    #   - TZ=America/Cuiaba
    volumes:
      - ./tomcat:/usr/local/tomcat
    ports:
      - 8080:8080
    network_mode: host

#NETWORK CONFIGURATION
# networks:
#   NET_LOCAL:
#     name: NET_LOCAL
#     driver: bridge
  # NET_212:
  #   name: NET_212
  #   driver: macvlan
  #   driver_opts: 
  #     parent: eno1
  #   #   macvlan_mode: bridge
  #   ipam:
  #     config:
  #       -
  #         subnet: 10.100.212.0/24
  #         gateway: 10.100.212.1
  #         aux_addresses:
  #           host: 10.100.212.65
#   NET_DOCKER:
#     name: NET_DOCKER
#     driver: ipvlan
#     driver_opts:
#       # parent: eth0.10
#       mode: l3
#     ipam:
#       config:
#         -
#           subnet: 10.1.10.0/24
#           gateway: 10.1.10.1

# volumes:
#   volmysqlghost:
#     name: volmysqlghost
#     driver: local
#   volghost:
#     name: volghost
#     driver: local

    # volumes:
    #   - type: bind
    #     source: /volume1/docker/influxdb2/data
    #     target: /var/lib/influxdb2
    #   - type: bind
    #     source: /volume1/docker/influxdb2/config
    #     target: /etc/influxdb2