version: '3.8'
services:
  centos:
    build: .
    container_name: container_centos
    image: kelseysantos/centos7:latest
    hostname: centos7
    networks:
      NET_212:
        ipv4_address: 10.100.212.203

#NETWORK CONFIGURATION
networks:
  NET_212:
    name: NET_212
    driver: macvlan
    driver_opts: 
      parent: eno1
    #   macvlan_mode: bridge
    ipam:
      config:
        -
          subnet: 10.100.212.0/24
          gateway: 10.100.212.1
          aux_addresses:
            host: 10.100.212.65