version: '3.9'

services:
#Status Docker
  doku:
    container_name: container_doku
    image: amerkurev/doku
    hostname: doku
    # cap_add:
    #   - NET_ADMIN
    #   - SYS_ADMIN 
    # restart: unless-stopped
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/:/hostroot:ro'
    ports:
      - '9090:9090'
    networks:
      NET_LOCAL:
#
# NETWORKS
networks:
  # NET_DOCKER:
  #   name: NET_DOCKER
  #   driver: ipvlan
  #   driver_opts:
  #     mode: l3
  #   ipam:
  #     config:
  #       - subnet: 10.1.10.0/24
  NET_LOCAL:
    name: NET_LOCAL
    driver: bridge
  # NET_212:
  #   name: NET_212
  #   driver: macvlan
  #   driver_opts: 
  #     parent: eno1
  #   #   macvlan_mode: bridge
  #   ipam:
  #     config:
  #       -
  #         subnet: 10.100.212.0/24
  #         gateway: 10.100.212.1
  #         aux_addresses:
  #           host: 10.100.212.65
# ip link add rededocker link eno1 type macvlan mode bridge
# ip addr add 10.100.212.65/32 dev rededocker
# ip link set rededocker up
# ip route add 10.100.212.0/24 dev rededocker
#