version: '3.9'

services:
#Status Docker
  doku:
    container_name: container_doku
    image: amerkurev/doku
    hostname: doku
    privileged: true
    # cap_add:
    #   - NET_ADMIN
    #   - SYS_ADMIN 
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/hostroot:ro
    ports:
      - '9090:9090'
    network_mode: host