version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: container_prometheus
    privileged: true
    # cap_add:
    #   - NET_ADMIN
    #   - SYS_ADMIN
    hostname: prometheus
    restart: unless-stopped
    # network_mode: bridge 
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
       - HOSTBRIDGE
    ports:
      - 9090:9090

#NETWORK MACVLAN CONFIGURATION
networks:
  HOSTBRIDGE:
    name: HOSTBRIDGE
    driver: bridge