# Configuração Prometheus Minio
# by Kelsey Santos
global:
  scrape_interval: 15s
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

  # external_labels:
  #     monitor: 'example'

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['localhost:9093']

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "minio-alerting.yml"
  # - "second_rules.yml"

scrape_configs:
- job_name: minio-cluster
  bearer_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoicGpjbXRtaW5pbyIsImV4cCI6NDg0ODE0OTA5Nn0.SZxSwcj6zyo4_skQ_zhPKs6Wca-uBql09ASxzNYQsKmHpwUCYqI54qqiXvU77jgyOdxlRjKRw_EIQX6ph8gWTw
  metrics_path: /minio/v2/metrics/cluster
  scheme: http
  static_configs:
  - targets: ['localhost:9000', '10.8.4.52:9000', '10.8.4.53:9000']
- job_name: 'prometheus'
  # Override the global default and scrape targets from this job every 5 seconds.
  scrape_interval: 5s
  scrape_timeout: 5s
  # metrics_path defaults to '/metrics'
  # scheme defaults to 'http'.
  static_configs:
  - targets: ['localhost:9090']
- job_name: node
  # If prometheus-node-exporter is installed, grab stats about the local
  # machine by default.
  static_configs:
  - targets: ['localhost:9100']
- job_name: minio-job-bucket
  bearer_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoicGpjbXRtaW5pbyIsImV4cCI6NDg0ODE0OTA5Nn0.SZxSwcj6zyo4_skQ_zhPKs6Wca-uBql09ASxzNYQsKmHpwUCYqI54qqiXvU77jgyOdxlRjKRw_EIQX6ph8gWTw
  metrics_path: /minio/v2/metrics/bucket
  scheme: http
  static_configs:
  - targets: ['localhost:9000', '10.8.4.52:9000', '10.8.4.53:9000']
