version: '3.9'
services:
  emby:
    container_name: container_emby
    image: linuxserver/emby:latest
    hostname: emby
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGUI=1000
      - TZ=America/Cuiaba
    volumes:
      - ./config:/config
      - ./tvshows:/data/tvshows
      - ./movies:/data/movies
      - ./lib:/opt/vc/lib
    ports:
      - 8096:8096
      - 8920:8920
    network_mode: host