version: '3.8'
services:
# PORTAINER CE
  portainerce:
    container_name: container_portainerce
    image: portainer/portainer-ce:latest
    hostname: portainer
    privileged: true
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    #   - SYS_ADMIN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - volportainerce:/data
    ports:
      - 19000:9000
      - 19443:9443
      - 18000:8000
    network_mode: bridge
# VOLUMES
volumes:
  volportainerce:
    name: volportainerce
    driver: local
#