version: '3.9'
services:
  gitlab:
    # build: .
    container_name: container_gitlab
    image: gitlab/gitlab-ce:latest
    hostname: gitlab
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Cuiaba
    volumes:
      - ./etc:/etc/gitlab
      - ./opt:/var/opt/gitlab
      - ./log:/var/log/gitlab
    ports:
      - 22:22
      - 80:80
      - 443:443
    network_mode: host