version: '3.5'
services:
  dashdot:
    image: mauricenino/dashdot:latest
    container_name: container_dashdot
    restart: unless-stopped
    hostname: dashdot
    privileged: true
    environment:
      - DASHDOT_ENABLE_CPU_TEMPS=true
      - DASHDOT_ENABLE_STORAGE_SPLIT_VIEW=true
      - DASHDOT_SHOW_HOST=true
      - DASHDOT_ALWAYS_SHOW_PERCENTAGES=true
    ports:
      - '83:3001'
    volumes:
      - /:/mnt/host:ro