version: '3.9'

services:
#

#
#Status Docker
  doku:
    container_name: container_doku
    image: amerkurev/doku
    hostname: doku
    # cap_add:
    #   - NET_ADMIN
    #   - SYS_ADMIN 
    # restart: unless-stopped
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/:/hostroot:ro'
    ports:
      - '9090:9090'
    networks:
      - green
#
#NETWORK CONFIGURATION
networks:
  # vlan10:
  #   name: NET_vlan10
  #   driver: ipvlan
  #   driver_opts:
  #     parent: eth0.10
  #     mode: l3
  #   ipam:
  #     config:
  #       - subnet: 10.1.10.0/24
  green:
    name: NET_green
    driver: bridge
#