version: '3.8'
services:
  alpine:
    build: .
    container_name: container_alpine
    image: kelseysantos/alpine:latest
    hostname: apline
    # deploy:
    #   placement:
    #     constraints:
    #         - "node.role==worker"
    #   mode: replicated
    #   replicas: 2
    #   resource:
    #     cpus: "0.50"
    #     memory: 256M
    # privileged: true
    # cap_add:
    #   - NET_ADMIN
    #   - SYS_ADMIN 
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Cuiaba
    # volumes:
    #   - ./www:/var/www/html:ro
    #   - ./php/php.ini:/usr/local/etc/php/php.ini:ro
    # ports:
    #   - 22:22
    network_mode: host

#NETWORK MACVLAN CONFIGURATION
# networks:
#   NET_LOCAL:
#     name: NET_LOCAL
#     driver: bridge
#   NET_212:
#     name: NET_212
#     driver: macvlan
#     driver_opts: 
#       parent: eno1
#     #   macvlan_mode: bridge
#     ipam:
#       config:
#         - subnet: 10.100.212.0/24
#           #ip_range: 10.100.212.65/26
#           gateway: 10.100.212.1
#           aux_addresses:
#             host: 10.100.212.65
#   NET_DOCKER:
#     name: NET_DOCKER
#     driver: ipvlan
#     driver_opts:
#       # parent: eth0.10
#       mode: l3
#     ipam:
#       config:
#         -
#           subnet: 10.1.10.0/24
#           gateway: 10.1.10.1

# volumes:
#   volmysqlghost:
#     name: volmysqlghost
#     driver: local
#   volghost:
#     name: volghost
#     driver: local

# volumes:
#   - type: bind
#     source: /volume1/docker/influxdb2/data
#     target: /var/lib/influxdb2
#   - type: bind
#     source: /volume1/docker/influxdb2/config
#     target: /etc/influxdb2