# version: '3.9'
services:
  deluge:
    container_name: container_deluge
    image: linuxserver/deluge:latest
    hostname: deluge
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Cuiaba
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    network_mode: host