version: '3.8'
services:
  rockylinux:
    build: .
    container_name: container_rockylinux
    image: kelseysantos/rockylinux:dns
    privileged: true
    # cap_add:
    #   - NET_ADMIN
    #   - SYS_ADMIN
    hostname: dns1
    networks:
      NET_212:
        ipv4_address: 10.100.212.203

#NETWORK MACVLAN CONFIGURATION
networks:
  NET_212:
    name: NET_212
    driver: macvlan
    driver_opts: 
      parent: eno1
    #   macvlan_mode: bridge
    ipam:
      config:
        - subnet: 10.100.212.0/24
          #ip_range: 10.100.212.65/26
          gateway: 10.100.212.1
          aux_addresses:
            host: 10.100.212.65