version: '3.9'
services:
  filezilla:
    container_name: container_filezilla
    image: linuxserver/filezilla:latest
    hostname: filezilla
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Cuiaba 
    volumes:
      - ./config:/config
    ports:
      - 3000:3000
    network_mode: host
