version: '3.9'
services:
  mysql:
    container_name: container_mysql
    image: mysql:latest
    hostname: mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=dbmysql
      - MYSQL_USER=usermysql
      - MYSQL_PASSWORD=passmysql
      - MYSQL_ROOT_PASSWORD=kelseysantos
      - TZ=America/Cuiaba
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    network_mode: host