version: '3.9'
services:
  wireshark:
    container_name: container_wireshark
    image: linuxserver/wireshark:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Cuiaba
    volumes:
      - ./config:/config
    ports:
      - 3000:3000
    # networks:
    #   NET_212:
    #     ipv4_address: 10.100.212.203
