version: '3.8'

services:
#
  minio-0:
    image: 'bitnami/minio:latest'
    volumes:
      - 'minio_0_data_0:/data-0'
      - 'minio_0_data_1:/data-1'
    environment:
      - MINIO_ROOT_USER=kelsey
      - MINIO_ROOT_PASSWORD=kelseysantos
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio-{0...1}/data-{0...1}
#
  minio-1:
    image: 'bitnami/minio:latest'
    volumes:
      - 'minio_1_data_0:/data-0'
      - 'minio_1_data_1:/data-1'
    environment:
      - MINIO_ROOT_USER=kelsey
      - MINIO_ROOT_PASSWORD=kelseysantos
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio-{0...1}/data-{0...1}
#
volumes:
  minio_0_data_0:
    driver: local
  minio_0_data_1:
    driver: local
  minio_1_data_0:
    driver: local
  minio_1_data_1:
    driver: local
#
#NETWORK CONFIGURATION
networks:
  vlan10:
    name: NET_vlan10
    driver: ipvlan
    driver_opts:
      parent: eth0.10
      mode: l3
    ipam:
      config:
        - subnet: 10.1.10.0/24
  green:
    name: NET_green
    driver: bridge
#