version: '3.9'
services:
#Server MINIO 0
  miniobkp:
    image: bitnami/minio:latest
    container_name: container_miniobkp
    hostname: miniobkp
    restart: always
    environment:
      - MINIO_ROOT_USER=pjcmtminio
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - volminio0:/data:rw
      - volminiocerts:/certs:rw
    networks:
      - NET_LOCAL
    ports:
      - '9000:9000'
      - '9001:9001'
#
#NETWORK CONFIGURATION
networks:
  NET_LOCAL:
    name: NET_LOCAL
    driver: bridge
#
# VOLUMES
volumes:
  volminio0:
    name: volminio0
    driver: local
  volminiocerts:
    name: volminiocerts
    driver: local
#