version: '3.8'

services:
#Server MINIO 01
  srv01:
    image: bitnami/minio:latest
    container_name: container_srv01
    hostname: srv01
    # restart: always
    environment:
      - MINIO_ROOT_USER=kelsey
      - MINIO_ROOT_PASSWORD=kelseysantos
    volumes:
      - volnode0:/data
      - volnode0:/certs
    networks:
      NET_212:
        ipv4_address: 10.100.212.80
    ports:
      - '9000:9000'
      - '9001:9001'
#
#Server MINIO REPLICATION
  srv02:
    image: bitnami/minio:latest
    container_name: container_srv02
    hostname: srv02
    # restart: always
    environment:
      - MINIO_ROOT_USER=kelsey
      - MINIO_ROOT_PASSWORD=kelseysantos
    volumes:
      - volnode1:/data
      - volnode1:/certs
    networks:
      NET_212:
        ipv4_address: 10.100.212.81
    ports:
      - '9000:9000'
      - '9001:9001'
#
#Server MINIO REPLICATION
  srv03:
    image: bitnami/minio:latest
    container_name: container_srv03
    hostname: srv03
    # restart: always
    environment:
      - MINIO_ROOT_USER=kelsey
      - MINIO_ROOT_PASSWORD=kelseysantos
    volumes:
      - volnode2:/data
      - volnode2:/certs
    networks:
      NET_212:
        ipv4_address: 10.100.212.82
    ports:
      - '9000:9000'
      - '9001:9001'
#
#NETWORK CONFIGURATION
networks:
  NET_212:
    name: NET_212
    driver: macvlan
    driver_opts: 
      parent: eno1
    #   macvlan_mode: bridge
    ipam:
      config:
        -
          subnet: 10.100.212.0/24
          gateway: 10.100.212.1
          aux_addresses:
            host: 10.100.212.65
#
# VOLUMES
volumes:
  volnode0:
    name: volnode0
    driver: local
  volnode1:
    name: volnode1
    driver: local
  volnode2:
    name: volnode2
    driver: local
#