version: '3.8'

services:
#
  minio0:
    image: 'bitnami/minio:latest'
    container_name: container_minio0
    volumes:
      - ./volumes/00:/data-0
      - ./volumes/01:/data-1
      - ./volumes/02:/data-2
      - ./volumes/03:/data-3
      - ./volumes/04:/data-4
      - ./volumes/05:/data-5
      # - ./volumes/06:/data-6
      # - ./volumes/07:/data-7
      # - ./volumes/08:/data-8
      # - ./volumes/09:/data-9
      # - ./volumes/10:/data-10
      # - ./volumes/11:/data-11
    environment:
      - MINIO_ROOT_USER=kelsey
      - MINIO_ROOT_PASSWORD=kelseysantos
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio{0...1}/data-{0...5}
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      green:
      vlan10: 
        ipv4_address: 10.1.10.10
#
  minio1:
    image: 'bitnami/minio:latest'
    container_name: container_minio1
    volumes:
      - ./volumes/12:/data-0
      - ./volumes/13:/data-1
      - ./volumes/14:/data-2
      - ./volumes/15:/data-3
      - ./volumes/16:/data-4
      - ./volumes/17:/data-5
      # - ./volumes/18:/data-6
      # - ./volumes/19:/data-7
      # - ./volumes/20:/data-8
      # - ./volumes/21:/data-9
      # - ./volumes/22:/data-10
      # - ./volumes/23:/data-11
    environment:
      - MINIO_ROOT_USER=kelsey
      - MINIO_ROOT_PASSWORD=kelseysantos
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio{0...1}/data-{0...5}
    ports:
      - '9002:9000'
      - '9003:9001'
    networks:
      # green:
      vlan10: 
        ipv4_address: 10.1.10.11
#
#NETWORK CONFIGURATION
networks:
  vlan10:
    name: NET_vlan10
    driver: ipvlan
    driver_opts:
      parent: eth0.10
      mode: l3
    ipam:
      config:
        - subnet: 10.1.10.0/24
  green:
    name: NET_green
    driver: bridge
#