version: '3.9'
services:
#

#NETWORK CONFIGURATION
networks:
  NET_LOCAL:
    name: NET_LOCAL
    driver: bridge
#
# VOLUMES
volumes:
  volminio0:
    name: volminio0
    driver: local
  volminiocerts:
    name: volminiocerts
    driver: local
#