version: '3.8'

services:
#
  minio-0:
    image: 'bitnami/minio:latest'
    container_name: container_minio-0
    volumes:
      - ./volumes/00:/data-0
      - ./volumes/01:/data-1
      # - 'minio_0_data_0:/data-0'
      # - 'minio_0_data_1:/data-1'
    environment:
      - MINIO_ROOT_USER=kelsey
      - MINIO_ROOT_PASSWORD=kelseysantos
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio-{0...3}/data-{0...3}
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      green:
      vlan10: 
        ipv4_address: 10.1.10.10
#
  minio-1:
    image: 'bitnami/minio:latest'
    container_name: container_minio-1
    volumes:
      - ./volumes/10:/data-0
      - ./volumes/11:/data-1
      # - 'minio_1_data_0:/data-0'
      # - 'minio_1_data_1:/data-1'
    environment:
      - MINIO_ROOT_USER=kelsey
      - MINIO_ROOT_PASSWORD=kelseysantos
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio-{0...9}/data-{0...9}
    # ports:
    #   - '9000:9000'
    #   - '9001:9001'
    networks:
      # green:
      vlan10: 
        ipv4_address: 10.1.10.11
#
# volumes:
#   minio_0_data_0:
#     driver: local
#   minio_0_data_1:
#     driver: local
#   minio_1_data_0:
#     driver: local
#   minio_1_data_1:
#     driver: local
#
#NETWORK CONFIGURATION
networks:
  vlan10:
    name: NET_vlan10
    driver: ipvlan
    driver_opts:
      parent: eth0.10
      mode: l3
    ipam:
      config:
        - subnet: 10.1.10.0/24
  green:
    name: NET_green
    driver: bridge
#