version: '3.8'
services:
  minio0:
    image: 'minio/minio:latest'
    container_name: container_minio0
    hostname: minio0
    restart: always
    environment:
      - MINIO_ROOT_USER=kelsey
      - MINIO_ROOT_PASSWORD=kelseysantos
      # - MINIO_OPTS="--console-address :9001"
      # - MINIO_VOLUMES="/disco{0...11}"
      # - MINIO_STORAGE_CLASS_STANDARD="EC:5"
      # - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      # - MINIO_DISTRIBUTED_NODES=minio{0...2}/disco{1...12}
    command: server --console-address ":9001" http://minio{0...2}:9000/disco{1...12}
    volumes:
      - volminio0:/data
      # - volminiocerts:/certs
      - ./volumes/minio0/disco1:/disco1
      - ./volumes/minio0/disco2:/disco2
      - ./volumes/minio0/disco3:/disco3
      - ./volumes/minio0/disco4:/disco4
      - ./volumes/minio0/disco5:/disco5
      - ./volumes/minio0/disco6:/disco6
      - ./volumes/minio0/disco7:/disco7
      - ./volumes/minio0/disco8:/disco8
      - ./volumes/minio0/disco9:/disco9
      - ./volumes/minio0/disco10:/disco10
      - ./volumes/minio0/disco11:/disco11
      - ./volumes/minio0/disco12:/disco12
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      NET_212:
        ipv4_address: 10.100.212.100
  minio1:
      image: 'minio/minio:latest'
      container_name: container_minio1
      hostname: minio1
      restart: always
      depends_on:
        - minio0
      environment:
        - MINIO_ROOT_USER=kelsey
        - MINIO_ROOT_PASSWORD=kelseysantos
        # - MINIO_OPTS="--console-address :9001"
        # - MINIO_VOLUMES="/disco{0...11}"
        # - MINIO_STORAGE_CLASS_STANDARD="EC:5"
        # - MINIO_DISTRIBUTED_MODE_ENABLED=yes
        # - MINIO_DISTRIBUTED_NODES=minio{0...2}/disco{1...12}
      command: server --console-address ":9001" http://minio{0...2}:9000/disco{1...12}
      volumes:
        - volminio1:/data
        # - volminiocerts:/certs
        - ./volumes/minio1/disco1:/disco1
        - ./volumes/minio1/disco2:/disco2
        - ./volumes/minio1/disco3:/disco3
        - ./volumes/minio1/disco4:/disco4
        - ./volumes/minio1/disco5:/disco5
        - ./volumes/minio1/disco6:/disco6
        - ./volumes/minio1/disco7:/disco7
        - ./volumes/minio1/disco8:/disco8
        - ./volumes/minio1/disco9:/disco9
        - ./volumes/minio1/disco10:/disco10
        - ./volumes/minio1/disco11:/disco11
        - ./volumes/minio1/disco12:/disco12
      ports:
        - '9000:9000'
        - '9001:9001'
      networks:
        NET_212:
          ipv4_address: 10.100.212.101
  minio2:
      image: 'minio/minio:latest'
      container_name: container_minio2
      hostname: minio2
      restart: always
      depends_on:
        - minio0
      environment:
        - MINIO_ROOT_USER=kelsey
        - MINIO_ROOT_PASSWORD=kelseysantos
        # - MINIO_OPTS="--console-address :9001"
        # - MINIO_VOLUMES="/disco{0...11}"
        # - MINIO_STORAGE_CLASS_STANDARD="EC:5"
        # - MINIO_DISTRIBUTED_MODE_ENABLED=yes
        # - MINIO_DISTRIBUTED_NODES=minio{0...2}/disco{1...12}
      command: server --console-address ":9001" http://minio{0...2}:9000/disco{1...12}
      volumes:
        - volminio2:/data
        # - volminiocerts:/certs
        - ./volumes/minio2/disco1:/disco1
        - ./volumes/minio2/disco2:/disco2
        - ./volumes/minio2/disco3:/disco3
        - ./volumes/minio2/disco4:/disco4
        - ./volumes/minio2/disco5:/disco5
        - ./volumes/minio2/disco6:/disco6
        - ./volumes/minio2/disco7:/disco7
        - ./volumes/minio2/disco8:/disco8
        - ./volumes/minio2/disco9:/disco9
        - ./volumes/minio2/disco10:/disco10
        - ./volumes/minio2/disco11:/disco11
        - ./volumes/minio2/disco12:/disco12
      ports:
        - '9000:9000'
        - '9001:9001'
      networks:
        NET_212:
          ipv4_address: 10.100.212.102
#
#NETWORK CONFIGURATION
networks:
  NET_212:
    name: NET_212
    driver: macvlan
    driver_opts: 
      parent: eno1
    #   macvlan_mode: bridge
    ipam:
      config:
        -
          subnet: 10.100.212.0/24
          gateway: 10.100.212.1
          aux_addresses:
            host: 10.100.212.65
#
volumes:
  volminio0:
    name: volminio0
    driver: local
  volminio1:
    name: volminio1
    driver: local
  volminio2:
    name: volminio2
    driver: local