version: '3.8'

services:
#Server MINIO 01
  miniomaster:
    # build: ./images/minio
    image: bitnami/minio:latest
    container_name: container_miniomaster
    hostname: miniomaster
    environment:
      - MINIO_ROOT_USER=kelsey
      - MINIO_ROOT_PASSWORD=kelseysantos
      # - MINIO_SCHEME=https
      # - MINIO_SERVER_URL=https://localhost
      # - MINIO_ACCESS_KEY=EeyKGV8sW6eNbq2o
      # - MINIO_SECRET_KEY=gIxr84JBcWiZ7pKfScS8zNl6Spkc3I5D
    volumes:
      - ./volumes/hd0:/data
      # - ./volumes/hd0/certs:/certs
    networks:
      green:
      vlan10:
        ipv4_address: 10.1.10.10
    ports:
      - '9000:9000'
      - '9001:9001'
    restart: always
#
#NETWORK CONFIGURATION
networks:
  vlan10:
    name: NET_vlan10
    driver: ipvlan
    driver_opts:
      parent: eth0.10
      mode: l3
    ipam:
      config:
        - subnet: 10.1.10.0/24
  green:
    name: NET_green
    driver: bridge
#