version: '3.8'

services:
#Server MINIO 01
  miniomaster:
    image: bitnami/minio:latest
    container_name: container_miniomaster
    hostname: miniomaster
    # restart: always
    environment:
      - MINIO_ROOT_USER=kelsey
      - MINIO_ROOT_PASSWORD=kelseysantos
      # - MINIO_OPTS="--console-address :9001"
      - MINIO_VOLUMES="/storages/minio/disk{0...11}"
    volumes:
      - volnode0:/data
      - volnode0:/certs
    networks:
      - NET_LOCAL
    ports:
      - '9000:9000'
      - '9001:9001'
#
#NETWORK CONFIGURATION
networks:
  NET_LOCAL:
    name: NET_LOCAL
    driver: bridge
#
# VOLUMES
volumes:
  volnode0:
    name: volnode0
    driver: local
#