version: '3.8'

services:
#Server MINIO 01
  miniomaster:
    image: bitnami/minio:latest
    container_name: container_miniomaster
    hostname: miniomaster
    environment:
      - MINIO_ROOT_USER=kelsey
      - MINIO_ROOT_PASSWORD=kelseysantos
    volumes:
      - volnode0:/data
      - volnode0:/certs
    networks:
      # green:
      NET_212:
        ipv4_address: 10.100.212.60
    ports:
      - '9000:9000'
      - '9001:9001'
    restart: always
#
#NETWORK CONFIGURATION
networks:
  green:
    name: NET_green
    driver: bridge
  NET_212:
    name: NET_212
    driver: macvlan
    driver_opts: 
      parent: eno1
    #   macvlan_mode: bridge
    ipam:
      config:
        -
          subnet: 10.100.212.0/24
          gateway: 10.100.212.1
          aux_addresses:
            host: 10.100.212.65
#
# VOLUMES
volumes:
  volnode0:
    driver: local
#