version: '3.8'
services:
#Server MINIO 0
  minioone:
    image: bitnami/minio:latest
    container_name: container_minioone
    hostname: minioone
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER=kelsey
      - MINIO_ROOT_PASSWORD=kelseysantos
      # - MINIO_VOLUMES="./volumes/minioone/disk{0...11}"
    volumes:
      - volminioone:/data:rw
      - volminioonecerts:/certs:rw
    ports:
      - '9000:9000'
      - '9001:9001'
    network_mode: host
#
# VOLUMES
volumes:
  volminioone:
    name: volminioone
    driver: local
  volminioonecerts:
    name: volminioonecerts
    driver: local
#