version: '3.9'
services:
  emulatorjs:
    container_name: container_emulatorjs
    image: linuxserver/emulatorjs:latest
    hostname: emulatorjs
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Cuiaba
      # - SUBFOLDER=/ 
    volumes:
      - ./emulatorjs/config:/config
      - ./emulatorjs/data:/data
    ports:
      - 80:80
      # - 443:443
      - 3000:3000
      - 4001:4001
    networks:
      NET_212:
        ipv4_address: 10.100.212.203

#NETWORK CONFIGURATION
networks:
  # NET_LOCAL:
  #   name: NET_LOCAL
  #   driver: bridge
  NET_212:
    name: NET_212
    driver: macvlan
    driver_opts: 
      parent: eno1
    #   macvlan_mode: bridge
    ipam:
      config:
        -
          subnet: 10.100.212.0/24
          gateway: 10.100.212.1
          aux_addresses:
            host: 10.100.212.65
  # NET_DOCKER:
  #   name: NET_DOCKER
  #   driver: ipvlan
  #   driver_opts:
  #     # parent: eth0.10
  #     mode: l3
  #   ipam:
  #     config:
  #       -
  #         subnet: 10.1.10.0/24
  #         gateway: 10.1.10.1