version: '3.9'
services:
  emulatorjs:
    container_name: container_emulatorjs
    image: linuxserver/emulatorjs:latest
    hostname: emulatorjs
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Cuiaba
      # - SUBFOLDER=/ 
    volumes:
      - ./emulatorjs/config:/config
      - ./emulatorjs/data:/data
    ports:
      - 80:80
      # - 443:443
      - 3000:3000
      - 4001:4001
    network_mode: host
